feat: add `make_immutable` to be on par with `make_dataclass`

diff --git a/.github/workflows/integration_delivery.yml b/.github/workflows/integration_delivery.yml
--- a/.github/workflows/integration_delivery.yml
+++ b/.github/workflows/integration_delivery.yml
@@ -6,7 +6,7 @@ on:
   workflow_dispatch:
 
 env:
-  PYTHON_VERSION: "3.11"
+  PYTHON_VERSION: '3.11'
 
 jobs:
   dependencies:
@@ -16,7 +16,7 @@ jobs:
       - uses: actions/checkout@v4
         name: Checkout
 
-      - name: Save Cached Poetry
+      - name: Load Cached Poetry
         id: cached-poetry
         uses: actions/cache@v4
         with:
@@ -99,8 +99,8 @@ jobs:
       - dependencies
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.extract_version.outputs.version }}
-      name: ${{ steps.extract_version.outputs.name }}
+      version: ${{ steps.extract_version.outputs.VERSION }}
+      name: ${{ steps.extract_version.outputs.NAME }}
     steps:
       - uses: actions/checkout@v4
         name: Checkout
@@ -120,14 +120,41 @@ jobs:
             ~/.local
           key: poetry-${{ hashFiles('poetry.lock') }}
 
-      - name: Build
-        run: poetry build
-
       - name: Extract Version
         id: extract_version
         run: |
-          echo "version=$(poetry version --short)" >> "$GITHUB_OUTPUT"
-          echo "name=$(poetry version | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
+          echo "VERSION=$(poetry version --short)" >> "$GITHUB_OUTPUT"
+          echo "NAME=$(poetry version | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
+          echo "VERSION=$(poetry version --short)"
+          echo "NAME=$(poetry version | cut -d' ' -f1)"
+
+      - name: Extract Version from CHANGELOG.md
+        id: extract_changelog_version
+        run: |
+          VERSION_CHANGELOG=$(sed -n '3 s/## Version //p' CHANGELOG.md) 
+          echo "VERSION_CHANGELOG=$VERSION_CHANGELOG"
+          if [ "${{ steps.extract_version.outputs.VERSION }}" != "$VERSION_CHANGELOG" ]; then
+            echo "Error: Version extracted from CHANGELOG.md does not match the version in pyproject.toml"
+            exit 1 
+          else
+            echo "Versions are consistent."
+          fi
+
+      - name: Extract Version from Tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        id: extract_tag_version
+        run: |
+          VERSION_TAG=$(sed 's/^v//' <<< ${{ github.ref_name }})
+          echo "VERSION_TAG=$VERSION_TAG"
+          if [ "${{ steps.extract_version.outputs.VERSION }}" != "$VERSION_TAG" ]; then
+            echo "Error: Version extracted from tag does not match the version in pyproject.toml"
+            exit 1 
+          else
+            echo "Versions are consistent."
+          fi
+
+      - name: Build
+        run: poetry build
 
       - name: Upload wheel
         uses: actions/upload-artifact@v4
@@ -175,19 +202,19 @@ jobs:
           verbose: true
 
   release:
+    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
     name: Release
     needs:
       - type-check
       - lint
       - build
       - pypi-publish
+    runs-on: ubuntu-latest
     environment:
       name: release
       url: https://pypi.org/p/${{ needs.build.outputs.name }}
-    runs-on: ubuntu-latest
     permissions:
       contents: write
-    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
     steps:
       - name: Procure Wheel
         uses: actions/download-artifact@v4
@@ -201,13 +228,28 @@ jobs:
           name: binary
           path: artifacts
 
+      - uses: actions/checkout@v4
+        name: Checkout
+
+      - name: Extract Changelog
+        id: changelog
+        run: |
+          perl -0777 -ne 'while (/## Version ${{ needs.build.outputs.version }}\n(\s*\n)*(.*?)(\s*\n)*## Version \d+\.\d+\.\d+\n/sg) {print "$2\n"}' CHANGELOG.md > CURRENT_CHANGELOG.md
+          {
+            echo "CONTENT<<EOF"
+            cat CURRENT_CHANGELOG.md
+            echo "EOF"
+          } >> "$GITHUB_OUTPUT"
+
       - name: Release
-        uses: softprops/action-gh-release@v1
+        uses: softprops/action-gh-release@v2
         with:
           files: artifacts/*
           tag_name: v${{ needs.build.outputs.version }}
           body: |
-            Release of version ${{ needs.build.outputs.version }}
             PyPI package: https://pypi.org/project/${{ needs.build.outputs.name }}/${{ needs.build.outputs.version }}
+
+            # Changes:
+            ${{ steps.changelog.outputs.CONTENT }}
           prerelease: false
           draft: false
